### ISSUE TITLE
Application Not Loading Properly When Find By Location is Enabled

### ISSUE THREAD

**Issue by gschwitz** [Esri/SimpleViewer#2]
Hello,
I have downloaded the application and everything works fine when adding my own webmap id.  However, when I configure the search by feature location in the webmap, it does not load properly.  I receive an "ReferenceError: FeatureLayer is not defined" error after enabling the search.  Any reason this would cause the application to not load properly?

Thanks,
Geoff

![simpleviewerscreenshot](https://cloud.githubusercontent.com/assets/8998866/6951606/7d79bcee-d88a-11e4-9d40-00495ff80681.jpg)

**Comment by kellyhutchins** [comment]
This is a bug that was fixed in Online but I didn't move the update here. It's fixed now. If you download the zip again it should work for you.

**Comment by gschwitz** [comment]
Thank You!
