### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by tscottmsu** [Esri/SimpleViewer#3]
I have downloaded and deployed the application with no issues. I used the app ID to load a template that I had created on ArcGIS Online. In the template, I have the basemaps widget enabled as well as a splash screen. It does not show up on my application when loaded from my server.

**Comment by tscottmsu** [comment]
Still having this issue, does anyone have any ideas?

**Comment by kellyhutchins** [comment]
@tscottmsu  are there any errors in the developer console? Are you sure the appid is for the same configurable app that you downloaded and deployed?

**Comment by tscottmsu** [comment]
Yes and yes.

**Comment by kellyhutchins** [comment]
@tscottmsu  I'll need more details in order to be able to help. Is the application id you are using public? If so can you provide that id. What are the error messages you see in the console?

**Comment by tscottmsu** [comment]
Yes the map and the application are both made public. I'd be happy to PM you them! I have no errors in the console.
